// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckURLHealth(arg1) {
  return window['go']['main']['App']['CheckURLHealth'](arg1);
}

export function GetVideoServerURL() {
  return window['go']['main']['App']['GetVideoServerURL']();
}

export function StartVideoServer() {
  return window['go']['main']['App']['StartVideoServer']();
}
